1. Numpy array creation and reshape it to a 2*5 matrix

In [ ]:
import numpy as np

arr = np.arange(1, 11)
matrix = arr.reshape(2, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2. Numpy array creation and extract the elements between 5th and 15th

In [ ]:
arr = np.arange(1, 21)
subset = arr[5:16]

print(subset)

[ 6  7  8  9 10 11 12 13 14 15 16]


3. Mean, Median and Standard deviation of numpy array

In [ ]:
mean_val = np.mean(arr)
median_val = np.median(arr)
std_val = np.std(arr)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)

Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


4. Numpy to create 2D array x of shape (3,4) and 1D array y of shape (4,). Subtract y from x using broadcasting.

In [ ]:
x = np.array([[10, 11, 12, 13],
              [14, 15, 16, 17],
              [18, 19, 20, 21]])

y = np.array([1, 2, 3, 4])
result = x - y

print("Array x:")
print(x)

print("\nArray y:")
print(y)

print("\nResult after broadcasting (x - y):")
print(result)

Array x:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Array y:
[1 2 3 4]

Result after broadcasting (x - y):
[[ 9  9  9  9]
 [13 13 13 13]
 [17 17 17 17]]


5. Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

1) Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

2) Select the rows of the dataframe where the age is greater than or equal to 30.

3) Convert this dataframe to a CSV file and read that CSV file, and finally display the contents.

In [ ]:
import pandas as pd

data = {
    "name": ["Ann", "Joy", "Joseph", "David", "Stephy",
             "Franco", "Mariya", "Senna", "Joshua", "Helen"],
    "age": [20, 21, 22, 23, 24, 25, 26, 27, 28, 35],
    "gender": ["Female", "Male", "Male", "Male", "Female",
               "Male", "Female", "Female", "Male", "Female"]
}

df = pd.DataFrame(data)
print(df)

     name  age  gender
0     Ann   20  Female
1     Joy   21    Male
2  Joseph   22    Male
3   David   23    Male
4  Stephy   24  Female
5  Franco   25    Male
6  Mariya   26  Female
7   Senna   27  Female
8  Joshua   28    Male
9   Helen   35  Female


In [ ]:
# Add a new column called 'occupation'
df["occupation"] = [
    "Programmer", "Manager", "Analyst",
    "Programmer", "Manager", "Analyst",
    "Programmer", "Manager", "Analyst",
    "Programmer"
]
print(df)

     name  age  gender  occupation
0     Ann   20  Female  Programmer
1     Joy   21    Male     Manager
2  Joseph   22    Male     Analyst
3   David   23    Male  Programmer
4  Stephy   24  Female     Manager
5  Franco   25    Male     Analyst
6  Mariya   26  Female  Programmer
7   Senna   27  Female     Manager
8  Joshua   28    Male     Analyst
9   Helen   35  Female  Programmer


In [ ]:
# Select rows where age is greater than or equal to 30
age_30_and_above = df[df["age"] >= 30]
print(age_30_and_above)

    name  age  gender  occupation
9  Helen   35  Female  Programmer


In [ ]:
# Convert DataFrame to CSV
df.to_csv("data.csv", index=False)

# Read the CSV file
df_from_csv = pd.read_csv("data.csv")

# Display the contents
print(df_from_csv)

     name  age  gender  occupation
0     Ann   20  Female  Programmer
1     Joy   21    Male     Manager
2  Joseph   22    Male     Analyst
3   David   23    Male  Programmer
4  Stephy   24  Female     Manager
5  Franco   25    Male     Analyst
6  Mariya   26  Female  Programmer
7   Senna   27  Female     Manager
8  Joshua   28    Male     Analyst
9   Helen   35  Female  Programmer
